### ISSUE TITLE
md5图片流没有数据

### ISSUE THREAD

**Issue by liwenzlw** [yanceyZhang/wx-chatbot#2]
![image](https://user-images.githubusercontent.com/18142468/93037507-2de7e480-f675-11ea-95c6-0093a3cc4ef5.png)

我改成这样了
![image](https://user-images.githubusercontent.com/18142468/93037547-43f5a500-f675-11ea-8827-b5c2f3deac4f.png)

**Comment by yanceyZhang** [comment]
感谢指正，已修正
